import { apiGet, apiPost } from '@/api/request'

export const getMediumApi = (data: any) => apiPost('/MachineMange/GetMedium', data)
export const deleteMediumApi = (data: any) => apiPost('/MachineMange/deleteMedium', data)
export const getDeviceForMediumApi = (data: any) => apiPost('/MachineMange/getDeviceForMedium', data)

export const getLogDataApi = (data: any) => apiPost('/MachineMange/getLogData', data)
export const deleteLogIdsApi = (data: any) => apiPost('/MachineMange/deleteLogIds', data)

export const getWarningListApi = (data: any) => apiPost('/MachineMange/getWarningList', data)
export const setWarningProcessApi = (data: any) => apiPost('/MachineMange/setWarningProcess', data)

export const getOrderListApi = (data: any) => apiPost('/MachineMange/getOrderList', data)
export const doWorkApi = (data: any) => apiPost('/MachineMange/doWork', data)
export const getOrderListByDeviceApi = (data: any) => apiPost('/MachineMange/GetOrderListByDevice', data)

export const getDeviceApi = (data?: any) => apiPost('/MachineMange/getDevice', data)
export const deleteDeviceApi = (data: any) => apiPost('/MachineMange/deleteDevice', data)
export const addDeviceApi = (data: any) => apiPost('/MachineMange/addDevice', data)
export const updateDeviceApi = (data: any) => apiPost('/MachineMange/updateDevice', data)
export const calibrationAddressOfDeviceApi = (data: any) => apiPost('/MachineMange/CalibrationAddressOfDevice', data)
export const setDeviceNoWorkApi = (data: any) => apiPost('/MachineMange/setDeviceNoWork', data)
export const addDeviceBatchApi = (fileName?: string) => apiGet(`/MachineMange/addDeviceBatch?fileName=${fileName}`)
export const setStatusWithBatchApi = (data: any) => apiPost('/MachineMange/SetStatusWithBatch', data)
export const setNotActiveBatchApi = (data: any) => apiPost('/MachineMange/setNotActiveBatch', data)

export const getDeviceTypeApi = (data?: any) => apiPost('/MachineMange/getDeviceType', data)
export const getDeviceTypeByProductIdApi = (data: any) => apiPost('/MachineMange/getDeviceTypeByProductId', data)
export const addDeviceTypeApi = (data: any) => apiPost('/MachineMange/addDeviceType', data)
export const updateDeviceTypeApi = (data: any) => apiPost('/MachineMange/updateDeviceType', data)
export const deleteDeviceTypeApi = (data: any) => apiPost('/MachineMange/deleteDeviceType', data)
export const getDeviceStatusApi = () => apiGet('/MachineMange/getDeviceStatus')
export const getScreenClassApi = () => apiGet('/MachineMange/getScreenClass')

export const getProductApi = (data?: any) => apiPost('/MachineMange/getProduct', data)
export const addProductApi = (data: any) => apiPost('/MachineMange/addProduct', data)
export const deleteProductApi = (data: any) => apiPost('/MachineMange/deletrProduct', data)
export const getPeripheralApi = () => apiGet('/MachineMange/getPeripheral')
export const getEmpowerApi = (productId: any) => apiGet(`/MachineMange/getEmpower?productId=${productId}`)
export const authorizeProductApi = (data: any) => apiPost('/MachineMange/AuthorizeThePorduct', data)

export const getGarbageTypeApi = (data: any) => apiPost('/MachineMange/getGarbageType', data)
export const getGarbagePicApi = (data: any) => apiPost('/MachineMange/getGarbagePic', data)
export const deleteGarbageTypeApi = (data: any) => apiPost('/MachineMange/deleteGarbageType', data)
export const getPointsTypeApi = () => apiGet('/MachineMange/getPointsType')
export const addPointsTypeApi = (data: any) => apiPost('/MachineMange/addPointsType', data)
export const updatePointsTypeApi = (data: any) => apiPost('/MachineMange/updatePointsType', data)

export const addRuleApi = (data: any) => apiPost('/MachineMange/addRule', data)
export const updateRuleApi = (data: any) => apiPost('/MachineMange/updateRule', data)
export const getDeviceRuleApi = (data: any) => apiPost('/MachineMange/getDeviceRule', data)
export const deleteRuleApi = (data: any) => apiPost('/MachineMange/deleteRule', data)
export const publishRuleApi = (data: any) => apiPost('/MachineMange/publishRule', data)
export const getWorkableDeviceRuleApi = (data: any) => apiPost('/MachineMange/getWorkableDeviceRule', data)
export const setRuleApi = (data: any) => apiPost('/MachineMange/setRule', data)
export const getRulesForDepartmentApi = () => apiGet('/MachineMange/getRulesForDepartment')
export const setBatchRulesApi = (data: any) => apiPost('/MachineMange/setBatchRules', data)

export const sendParameterApi = (data: any) => apiPost('/MachineMange/sendParameter', data)
export const getChannelInfoApi = (data: any) => apiPost('/MachineMange/getChannelInfo', data)
export const getDeviceParameterApi = (data: any) => apiPost('/MachineMange/getDeviceParameter', data)
export const sendRTOApi = (data: any) => apiPost('/MachineMange/sendRTO', data)
export const getExternalUnitApi = () => apiGet('/MachineMange/getExternalUnit')
export const getRTOApi = () => apiGet('/MachineMange/getRTO')
export const updateChannelMaxApi = (data: any) => apiPost('/MachineMange/updateChannelMax', data)

export const deleteDeviceLedContentApi = (data: any) => apiPost('/MachineMange/DeleteDeviceLedContent', data)
export const getLedContentApi = (data: any) => apiPost('/MachineMange/getLedContent', data)
export const addDeviceLedContentApi = (data: any) => apiPost('/MachineMange/AddDeviceLedContent', data)
export const setLedContentApi = (data: any) => apiPost('/MachineMange/setLedContent', data)

export const getPointCountApi = () => apiGet('/MachineMange/GetPointCount')
export const getMemberCountApi = () => apiGet('/MachineMange/GetMemberCount')
export const getDeviceCountApi = () => apiGet('/MachineMange/GetDeviceCount')
export const getWarningCountApi = () => apiGet('/MachineMange/GetWarningCount')
export const getPointGroupByDepartmentApi = (item: any) => apiGet(`/MachineMange/PointGroupByDepartment?item=${item}`)
export const getDeviceGroupByDepartmentApi = (item: any) => apiGet(`/MachineMange/GetDeviceGroupByDepartment?item=${item}`)
export const orderStatisApi = (item: any) => apiGet(`/MachineMange/OrderStatis?item=${item}`)
export const memberIncrementApi = (item: any) => apiGet(`/MachineMange/memberIncrement?item=${item}`)

export const getAreaChinaApi = (config: any) => apiGet('/MachineManage/getAreaChina', config)
export const getPointsApi = (id: any) => apiGet(`/MachineMange/getPoints?id=${id}`)
export const getClearCountApi = (id: any) => apiGet(`/MachineMange/getClearCount?id=${id}`)
export const getChannelMapApi = (id: any) => apiGet(`/MachineMange/getCheannelMap?id=${id}`)
